#!/bin/bash

#SBATCH --job-name=simple        # Job name
#SBATCH --output=job.%j.out     # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=12        # Schedule one core
#SBATCH --time=10:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the Red or Brown queue

# load module
echo "Running on $(hostname):"
python3 main.py --dataset audio --dataset_dir data/Edm_Data
