accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
audio_length: 59049
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 48
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_path: ''
dataset: audio
dataset_dir: data/Edm_Data_2
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
finetuner_batch_size: 256
finetuner_checkpoint_path: ''
finetuner_learning_rate: 0.001
finetuner_max_epochs: 200
finetuner_mlp: 0
flush_logs_every_n_steps: null
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
learning_rate: 0.0003
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
optimizer: Adam
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
projection_dim: 64
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sample_rate: 22050
seed: 42
stochastic_weight_avg: false
strategy: null
supervised: 0
sync_batchnorm: false
temperature: 0.5
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
transforms_delay: 0.3
transforms_filters: 0.8
transforms_gain: 0.3
transforms_noise: 0.01
transforms_pitch: 0.6
transforms_polarity: 0.8
transforms_reverb: 0.6
val_check_interval: 1.0
weight_decay: 1.0e-06
weights_save_path: null
weights_summary: top
workers: 0
